default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hello_app_development

test:
  <<: *default
  database: hello_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>